`r if (knitr:::is_html_output()) '
'`

\newpage
# References {-}

Acharjya, D. P. (2009). Fundamental approach to discrete mathematics. New Age International.

Black, K., Asafu-Adjaye, J., Khan, N., Perera, N., Edwards, P., & Harris, M. (2007). *Australasian business statistics*. John Wiley & Sons.

Butenko, S., & Pardalos, P. M. (2014). Numerical methods and optimization: An introduction. CRC Press

Casella, G., & Berger, R. L. (2002). Statistical inference (Vol. 2, pp. 337-472).Pacific Grove, CA: Duxbury

Dass, H. K. (2008). ‘Complex Numbers’, Advanced Engineering Mathematics. S. Chand Publishing. pp. 474-520.

Lipschutz, S. (2000). Schaum’s Outline of Probability. McGraw Hill Professional.

Montgomery, D. C., Peck, E. A., & Vining, G. G. (2012). Introduction to linear regression analysis (Vol. 821). John Wiley & Sons.

Mendelson, E. (1970). Boolean algebra and switching circuits. McGraw-Hill Edition 2004.

Mood, A.M., Graybill, F.A. and Boes, D.C. (2007): Introduction to the Theory of Statistics, 3rd Edn. (Reprint). Tata McGraw-Hill Pub. Co. Ltd.

Salvatore, D., & Reagle, D. (2002). Statistics and Econometrics, Schaum’s Outline Series.

Shenk, A. (1988). Calculus and analytic geometry. Scott Foresman & Company.

Spiegel, M. R., & Stephens, L. J. (2017). Schaum’s outline of statistics. McGraw Hill Professional.

Stewart, J. (2003). Calculus: Early Transcendentals. Thomson Learning. Inc., Belmont, CA.

