--- 
title: "CM 1110 Fundamentals of Mathematics and Statistics"
author: "Dr. Priyanga D. Talagala"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::pdf_book
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
#- \fancyhead[CO,CE]{This is fancy header}
- \fancyfoot[CO,CE]{Prepared by Dr. Priyanga D. Talagala  (Copyright 2020 Priyanga D. Talagala)}
- \fancyfoot[LE,RO]{\thepage}
- \usepackage{wrapfig}
#- \usepackage{float}
- \usepackage{floatrow}
- \floatplacement{figure}{H}
- \floatplacement{table}{H}
#- \makeatletter\renewcommand*{\fps@figure}{H}\makeatother
- \usepackage{amsmath}
---

# Course Syllabus {-}

## Pre-requisites {-}

None 

## Learning Outcomes {-}

On successful completion of this module, students will be able to apply fundamental concepts in Mathematics and Statistics for real world problem solving.


## Outline Syllabus {-}

**Fundamentals of Mathematics**

-	Number Systems
-	Sequences and Series
-	Introduction to Logic
-	Boolean Algebra
-	Differentiation and Integration

**Fundamentals of Statistics**

- Descriptive Statistics
- Sets and Relations
- Random Variables
- Probability
- Correlation and Regression



## Method of Assessment {-}

- Mid-semester examination 
- End-semester examination 

## Lecturer {-}

Dr. Priyanga D. Talagala

## Schedule {-}

Lectures: 

- Monday [1.15 pm - 4.30 pm]

Tutorial:

- Thursday [1.15 pm - 4.30 pm]

Consultation time: 

- Tuesday [11.30 am to 12.30 pm]

## Copyright Notice {-}

My lectures and course materials, including presentations, tests, exams, outlines, and similar materials, are protected by copyright. I am the exclusive owner of copyright in those materials I create. I encourage you to take notes and make copies of course materials for your own educational use. However, you may not, nor may you knowingly allow others to reproduce or distribute lecture notes and course materials publicly without my express written consent.  